module(name = "palworld-server")

bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_pkg", version = "1.3.0")
bazel_dep(name = "rules_steam")

git_override(
    module_name = "rules_steam",
    commit = "856f8e8c3b6bc3f221f0f0d5c163020d5b2d05ec",
    remote = "https://github.com/lanofdoom/rules_steam.git",
)

steamapps = use_extension("//:steamapps.bzl", "steamapps_bzlmod")
use_repo(steamapps, "palworld_dedicated_server")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

oci.pull(
    name = "palworld-server-debian",
    image = "docker.io/library/debian",
    platforms = ["linux/amd64"],
    digest = "sha256:f324c7ff54321e8d9c588493a20244965938ce0aa50bbd1022d38010e9ffc4b1",
)
use_repo(oci, "palworld-server-debian", "palworld-server-debian_linux_amd64")
