module(name = "palworld-server")

bazel_dep(name = "bazel_skylib", version = "1.9.2")
bazel_dep(name = "rules_oci", version = "2.3.0")
bazel_dep(name = "rules_pkg", version = "1.2.0")
bazel_dep(name = "rules_steam")

git_override(
    module_name = "rules_steam",
    commit = "ef9c82e97a3bf6b8285b0043a7d72e71f2a88cad",
    remote = "https://github.com/lanofdoom/rules_steam.git",
)

steamapps = use_extension("//:steamapps.bzl", "steamapps_bzlmod")
use_repo(steamapps, "palworld_dedicated_server")

oci = use_extension("@rules_oci//oci:extensions.bzl", "oci")

oci.pull(
    name = "palworld-server-debian",
    image = "docker.io/library/debian",
    platforms = ["linux/amd64"],
    digest = "sha256:34cd9e9fd437c0a095ec39cb2e73422c9f30821b0d0848ed74fd0d43bae4d958",
)
use_repo(oci, "palworld-server-debian", "palworld-server-debian_linux_amd64")
